[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "beyinfinance-api"
version = "0.1.0"
description = "Finansal göstergeler sunan REST API"
readme = "README.rst"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
  { name = "Senin Adın", email = "sen@example.com" }
]
dependencies = [
  "fastapi",
  "uvicorn"
]

[project.urls]
Homepage = "https://github.com/kullaniciadi/beyinfinance-api"
Documentation = "https://beyinfinance.readthedocs.io/"
